### PR TITLE
Added some examples in Documentation

### PR DESCRIPTION
**Pull request by kanishkamisra**
Will work on others as soon as I figure how to use them :laughing: 

Hope this is fine!

### CODE REVIEW

**Comment by kanishkamisra** [comment]
Additionally, I may have some ideas for vignettes but I need some time to work on them, unless you and Dave have some other plans.

**Comment by thomasp85** [comment]
Let's hold for a bit with the vignette - I'm still thinking on how I want to introduce it, and I don't want you to waste your time

**Comment by thomasp85** [comment]
Can I get you to assign the animations to a variable and then comment out the `animate()` call. Otherwise the examples is going to take forever to run :-)

e.g.

```r
p <- ggplot(mtcars) + 
  geom_boxplot(aes(factor(cal), mpg)) + 
  transition_states(gear, 2, 1)

# animate(p)
```

**Comment by kanishkamisra** [comment]
Ohhh of course! Thank you for informing me of this :)

**Comment by thomasp85** [comment]
Thanks a lot

**Pull request merged**
